# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'http://repo.baichuan-ios.taobao.com/baichuanSDK/AliBCSpecs.git'
install! 'cocoapods', :deterministic_uuids => false

platform :ios, '8.0'
inhibit_all_warnings!

target 'localPodsReferenceFramework' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for localPodsReferenceFramework
  
  pod 'UMengUShare/UI', '6.2.1'
  pod 'UMengUShare/Social/WeChat', '6.2.1'
  pod 'UMengUShare/Social/QQ', '6.2.1'
  pod 'UMengUShare/Social/SMS','6.2.1'
  
  pod 'localPodOne',:path => "../localPodOne"
end

post_install do |installer_representation|
    # installer_representation.project.targets.each do |target| #cocoapds 0.37.2及以下
    installer_representation.pods_project.targets.each do |target|  #cocoapds 0.38以后的写法
        target.build_configurations.each do |config|
            # if config.name != 'Release'
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'COCOAPODS=1']
            # end
        end
    end
end
